### PR TITLE
Relax sequel version to allow use of recents versions

### PR DESCRIPTION
**Pull request by guilleiguaran**

### CODE REVIEW

**Comment by k0kubun** [comment]
I also filed: https://github.com/treasure-data/perfectqueue/pull/63

**Comment by k0kubun** [comment]
@kamipo I don't have perfectqueue.gem's owner permission. Could you cut a new release to rubygems.org?

**Comment by kamipo** [comment]
👍 Released now.

**Comment by k0kubun** [comment]
thanks!

**Pull request merged**
